// package ma.stage.website.entities;

// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.boot.CommandLineRunner;
// import org.springframework.stereotype.Component;

// import ma.stage.website.services.PaysService;

// import java.util.Arrays;
// import java.util.List;

// @Component
// public class DataLoader implements CommandLineRunner {
//      @Autowired
//      private PaysService paysService;

//      @Override
//      public void run(String... args) throws Exception {
//           // Supprimer tous les pays existants

//           List<Pays> paysList = Arrays.asList(
//                     new Pays("Afghanistan", "https://flagsapi.com/AF/flat/64.png"),
//                     new Pays("Albania", "https://flagsapi.com/AL/flat/64.png"),
//                     new Pays("Algeria", "https://flagsapi.com/DZ/flat/64.png"),
//                     new Pays("American Samoa", "https://flagsapi.com/AS/flat/64.png"),
//                     new Pays("Andorra", "https://flagsapi.com/AD/flat/64.png"),
//                     new Pays("Angola", "https://flagsapi.com/AO/flat/64.png"),
//                     new Pays("Antigua and Barbuda", "https://flagsapi.com/AG/flat/64.png"),
//                     new Pays("Argentina", "https://flagsapi.com/AR/flat/64.png"),
//                     new Pays("Armenia", "https://flagsapi.com/AM/flat/64.png"),
//                     new Pays("Aruba", "https://flagsapi.com/AW/flat/64.png"),
//                     new Pays("Australia", "https://flagsapi.com/AU/flat/64.png"),
//                     new Pays("Austria", "https://flagsapi.com/AT/flat/64.png"),
//                     new Pays("Azerbaijan", "https://flagsapi.com/AZ/flat/64.png"),
//                     new Pays("Bahamas", "https://flagsapi.com/BS/flat/64.png"),
//                     new Pays("Bahrain", "https://flagsapi.com/BH/flat/64.png"),
//                     new Pays("Bangladesh", "https://flagsapi.com/BD/flat/64.png"),
//                     new Pays("Barbados", "https://flagsapi.com/BB/flat/64.png"),
//                     new Pays("Belgium", "https://flagsapi.com/BE/flat/64.png"),
//                     new Pays("Belize", "https://flagsapi.com/BZ/flat/64.png"),
//                     new Pays("Benin", "https://flagsapi.com/BJ/flat/64.png"),
//                     new Pays("Bermuda", "https://flagsapi.com/BM/flat/64.png"),
//                     new Pays("Bhutan", "https://flagsapi.com/BT/flat/64.png"),
//                     new Pays("Bolivia", "https://flagsapi.com/BO/flat/64.png"),
//                     new Pays("Bosnia and Herzegovina", "https://flagsapi.com/BA/flat/64.png"),
//                     new Pays("Botswana", "https://flagsapi.com/BW/flat/64.png"),
//                     new Pays("Brazil", "https://flagsapi.com/BR/flat/64.png"),
//                     new Pays("British Virgin Islands", "https://flagsapi.com/VG/flat/64.png"),
//                     new Pays("Brunei", "https://flagsapi.com/BN/flat/64.png"),
//                     new Pays("Bulgaria", "https://flagsapi.com/BG/flat/64.png"),
//                     new Pays("Burkina Faso", "https://flagsapi.com/BF/flat/64.png"),
//                     new Pays("Burundi", "https://flagsapi.com/BI/flat/64.png"),
//                     new Pays("Cambodia", "https://flagsapi.com/KH/flat/64.png"),
//                     new Pays("Cameroon", "https://flagsapi.com/CM/flat/64.png"),
//                     new Pays("Canada", "https://flagsapi.com/CA/flat/64.png"),
//                     new Pays("Cape Verde", "https://flagsapi.com/CV/flat/64.png"),
//                     new Pays("Cayman Islands", "https://flagsapi.com/KY/flat/64.png"),
//                     new Pays("Central African Republic", "https://flagsapi.com/CF/flat/64.png"),
//                     new Pays("Chad", "https://flagsapi.com/TD/flat/64.png"),
//                     new Pays("Chile", "https://flagsapi.com/CL/flat/64.png"),
//                     new Pays("China", "https://flagsapi.com/CN/flat/64.png"),
//                     new Pays("Chinese Taipei", "https://flagsapi.com/TW/flat/64.png"),
//                     new Pays("Colombia", "https://flagsapi.com/CO/flat/64.png"),
//                     new Pays("Comoros", "https://flagsapi.com/KM/flat/64.png"),
//                     new Pays("Cook Islands", "https://flagsapi.com/CK/flat/64.png"),
//                     new Pays("Costa Rica", "https://flagsapi.com/CR/flat/64.png"),
//                     new Pays("Croatia", "https://flagsapi.com/HR/flat/64.png"),
//                     new Pays("Cuba", "https://flagsapi.com/CU/flat/64.png"),
//                     new Pays("Cyprus", "https://flagsapi.com/CY/flat/64.png"),
//                     new Pays("Czech Republic", "https://flagsapi.com/CZ/flat/64.png"),
//                     new Pays("Democratic Republic of the Congo",
//                               "https://flagsapi.com/CD/flat/64.png"),
//                     new Pays("Denmark", "https://flagsapi.com/DK/flat/64.png"),
//                     new Pays("Djibouti", "https://flagsapi.com/DJ/flat/64.png"),
//                     new Pays("Dominica", "https://flagsapi.com/DM/flat/64.png"),
//                     new Pays("Dominican Republic", "https://flagsapi.com/DO/flat/64.png"),
//                     new Pays("East Timor", "https://flagsapi.com/TL/flat/64.png"),
//                     new Pays("Ecuador", "https://flagsapi.com/EC/flat/64.png"),
//                     new Pays("Egypt", "https://flagsapi.com/EG/flat/64.png"),
//                     new Pays("El Salvador", "https://flagsapi.com/SV/flat/64.png"),
//                     new Pays("Equatorial Guinea", "https://flagsapi.com/GQ/flat/64.png"),
//                     new Pays("Eritrea", "https://flagsapi.com/ER/flat/64.png"),
//                     new Pays("Estonia", "https://flagsapi.com/EE/flat/64.png"),
//                     new Pays("Eswatini", "https://flagsapi.com/SZ/flat/64.png"),
//                     new Pays("Ethiopia", "https://flagsapi.com/ET/flat/64.png"),
//                     new Pays("Federated States of Micronesia",
//                               "https://flagsapi.com/FM/flat/64.png"),
//                     new Pays("Fiji", "https://flagsapi.com/FJ/flat/64.png"),
//                     new Pays("Finland", "https://flagsapi.com/FI/flat/64.png"),
//                     new Pays("France", "https://flagsapi.com/FR/flat/64.png"),
//                     new Pays("Gabon", "https://flagsapi.com/GA/flat/64.png"),
//                     new Pays("The Gambia", "https://flagsapi.com/GM/flat/64.png"),
//                     new Pays("Georgia", "https://flagsapi.com/GE/flat/64.png"),
//                     new Pays("Germany", "https://flagsapi.com/DE/flat/64.png"),
//                     new Pays("Ghana", "https://flagsapi.com/GH/flat/64.png"),
//                     new Pays("Great Britain", "https://flagsapi.com/GB/flat/64.png"),
//                     new Pays("Greece", "https://flagsapi.com/GR/flat/64.png"),
//                     new Pays("Grenada", "https://flagsapi.com/GD/flat/64.png"),
//                     new Pays("Guam", "https://flagsapi.com/GU/flat/64.png"),
//                     new Pays("Guatemala", "https://flagsapi.com/GT/flat/64.png"),
//                     new Pays("Guinea", "https://flagsapi.com/GN/flat/64.png"),
//                     new Pays("Guinea-Bissau", "https://flagsapi.com/GW/flat/64.png"),
//                     new Pays("Guyana", "https://flagsapi.com/GY/flat/64.png"),
//                     new Pays("Haiti", "https://flagsapi.com/HT/flat/64.png"),
//                     new Pays("Honduras", "https://flagsapi.com/HN/flat/64.png"),
//                     new Pays("Hong Kong", "https://flagsapi.com/HK/flat/64.png"),
//                     new Pays("Hungary", "https://flagsapi.com/HU/flat/64.png"),
//                     new Pays("Iceland", "https://flagsapi.com/IS/flat/64.png"),
//                     new Pays("India", "https://flagsapi.com/IN/flat/64.png"),

//                     new Pays("Indonesia", "https://flagsapi.com/ID/flat/64.png"),
//                     new Pays("Iran", "https://flagsapi.com/IR/flat/64.png"),
//                     new Pays("Iraq", "https://flagsapi.com/IQ/flat/64.png"),
//                     new Pays("Ireland", "https://flagsapi.com/IE/flat/64.png"),
//                     new Pays("Israel", "https://flagsapi.com/IL/flat/64.png"),
//                     new Pays("Italy", "https://flagsapi.com/IT/flat/64.png"),
//                     new Pays("Ivory Coast", "https://flagsapi.com/CI/flat/64.png"),
//                     new Pays("Jamaica", "https://flagsapi.com/JM/flat/64.png"),
//                     new Pays("Japan", "https://flagsapi.com/JP/flat/64.png"),
//                     new Pays("Jordan", "https://flagsapi.com/JO/flat/64.png"),
//                     new Pays("Kazakhstan", "https://flagsapi.com/KZ/flat/64.png"),
//                     new Pays("Kenya", "https://flagsapi.com/KE/flat/64.png"),
//                     new Pays("Kiribati", "https://flagsapi.com/KI/flat/64.png"),

//                     new Pays("Kuwait", "https://flagsapi.com/KW/flat/64.png"),
//                     new Pays("Kyrgyzstan", "https://flagsapi.com/KG/flat/64.png"),
//                     new Pays("Laos", "https://flagsapi.com/LA/flat/64.png"),
//                     new Pays("Latvia", "https://flagsapi.com/LV/flat/64.png"),
//                     new Pays("Lebanon", "https://flagsapi.com/LB/flat/64.png"),
//                     new Pays("Lesotho", "https://flagsapi.com/LS/flat/64.png"),
//                     new Pays("Liberia", "https://flagsapi.com/LR/flat/64.png"),
//                     new Pays("Libya", "https://flagsapi.com/LY/flat/64.png"),
//                     new Pays("Liechtenstein", "https://flagsapi.com/LI/flat/64.png"),
//                     new Pays("Lithuania", "https://flagsapi.com/LT/flat/64.png"),
//                     new Pays("Luxembourg", "https://flagsapi.com/LU/flat/64.png"),
//                     new Pays("Madagascar", "https://flagsapi.com/MG/flat/64.png"),
//                     new Pays("Malawi", "https://flagsapi.com/MW/flat/64.png"),
//                     new Pays("Malaysia", "https://flagsapi.com/MY/flat/64.png"),
//                     new Pays("Maldives", "https://flagsapi.com/MV/flat/64.png"),
//                     new Pays("Mali", "https://flagsapi.com/ML/flat/64.png"),
//                     new Pays("Malta", "https://flagsapi.com/MT/flat/64.png"),
//                     new Pays("Marshall Islands", "https://flagsapi.com/MH/flat/64.png"),
//                     new Pays("Mauritania", "https://flagsapi.com/MR/flat/64.png"),
//                     new Pays("Mauritius", "https://flagsapi.com/MU/flat/64.png"),
//                     new Pays("Mexico", "https://flagsapi.com/MX/flat/64.png"),
//                     new Pays("Moldova", "https://flagsapi.com/MD/flat/64.png"),
//                     new Pays("Monaco", "https://flagsapi.com/MC/flat/64.png"),
//                     new Pays("Mongolia", "https://flagsapi.com/MN/flat/64.png"),
//                     new Pays("Montenegro", "https://flagsapi.com/ME/flat/64.png"),
//                     new Pays("Morocco", "https://flagsapi.com/MA/flat/64.png"),
//                     new Pays("Mozambique", "https://flagsapi.com/MZ/flat/64.png"),
//                     new Pays("Myanmar", "https://flagsapi.com/MM/flat/64.png"),
//                     new Pays("Namibia", "https://flagsapi.com/NA/flat/64.png"),
//                     new Pays("Nauru", "https://flagsapi.com/NR/flat/64.png"),
//                     new Pays("Nepal", "https://flagsapi.com/NP/flat/64.png"),
//                     new Pays("Netherlands", "https://flagsapi.com/NL/flat/64.png"),
//                     new Pays("New Zealand", "https://flagsapi.com/NZ/flat/64.png"),
//                     new Pays("Nicaragua", "https://flagsapi.com/NI/flat/64.png"),
//                     new Pays("Niger", "https://flagsapi.com/NE/flat/64.png"),
//                     new Pays("Nigeria", "https://flagsapi.com/NG/flat/64.png"),
//                     new Pays("North Korea", "https://flagsapi.com/KP/flat/64.png"),
//                     new Pays("North Macedonia", "https://flagsapi.com/MK/flat/64.png"),
//                     new Pays("Norway", "https://flagsapi.com/NO/flat/64.png"),
//                     new Pays("Oman", "https://flagsapi.com/OM/flat/64.png"),
//                     new Pays("Pakistan", "https://flagsapi.com/PK/flat/64.png"),
//                     new Pays("Palau", "https://flagsapi.com/PW/flat/64.png"),
//                     new Pays("Palestine", "https://flagsapi.com/PS/flat/64.png"),
//                     new Pays("Panama", "https://flagsapi.com/PA/flat/64.png"),
//                     new Pays("Papua New Guinea", "https://flagsapi.com/PG/flat/64.png"),
//                     new Pays("Paraguay", "https://flagsapi.com/PY/flat/64.png"),
//                     new Pays("Peru", "https://flagsapi.com/PE/flat/64.png"),
//                     new Pays("Philippines", "https://flagsapi.com/PH/flat/64.png"),
//                     new Pays("Poland", "https://flagsapi.com/PL/flat/64.png"),
//                     new Pays("Portugal", "https://flagsapi.com/PT/flat/64.png"),
//                     new Pays("Puerto Rico", "https://flagsapi.com/PR/flat/64.png"),
//                     new Pays("Qatar", "https://flagsapi.com/QA/flat/64.png"),
//                     new Pays("Refugee Olympic Team", "https://flagsapi.com/RO/flat/64.png"),
//                     new Pays("Republic of the Congo", "https://flagsapi.com/CG/flat/64.png"),
//                     new Pays("Romania", "https://flagsapi.com/RO/flat/64.png"),
//                     new Pays("Rwanda", "https://flagsapi.com/RW/flat/64.png"),
//                     new Pays("Saint Kitts and Nevis", "https://flagsapi.com/KN/flat/64.png"),
//                     new Pays("Saint Lucia", "https://flagsapi.com/LC/flat/64.png"),
//                     new Pays("Saint Vincent and the Grenadines",
//                               "https://flagsapi.com/VC/flat/64.png"),
//                     new Pays("Samoa", "https://flagsapi.com/WS/flat/64.png"),
//                     new Pays("San Marino", "https://flagsapi.com/SM/flat/64.png"),
//                     new Pays("São Tomé and Príncipe", "https://flagsapi.com/ST/flat/64.png"),
//                     new Pays("Saudi Arabia", "https://flagsapi.com/SA/flat/64.png"),
//                     new Pays("Senegal", "https://flagsapi.com/SN/flat/64.png"),
//                     new Pays("Serbia", "https://flagsapi.com/RS/flat/64.png"),
//                     new Pays("Seychelles", "https://flagsapi.com/SC/flat/64.png"),
//                     new Pays("Sierra Leone", "https://flagsapi.com/SL/flat/64.png"),
//                     new Pays("Singapore", "https://flagsapi.com/SG/flat/64.png"),
//                     new Pays("Slovakia", "https://flagsapi.com/SK/flat/64.png"),
//                     new Pays("Slovenia", "https://flagsapi.com/SI/flat/64.png"),
//                     new Pays("Solomon Islands", "https://flagsapi.com/SB/flat/64.png"),
//                     new Pays("Somalia", "https://flagsapi.com/SO/flat/64.png"),
//                     new Pays("South Africa", "https://flagsapi.com/ZA/flat/64.png"),
//                     new Pays("South Korea", "https://flagsapi.com/KR/flat/64.png"),
//                     new Pays("South Sudan", "https://flagsapi.com/SS/flat/64.png"),
//                     new Pays("Spain", "https://flagsapi.com/ES/flat/64.png"),
//                     new Pays("Sri Lanka", "https://flagsapi.com/LK/flat/64.png"),
//                     new Pays("Sudan", "https://flagsapi.com/SD/flat/64.png"),
//                     new Pays("Suriname", "https://flagsapi.com/SR/flat/64.png"),
//                     new Pays("Sweden", "https://flagsapi.com/SE/flat/64.png"),
//                     new Pays("Switzerland", "https://flagsapi.com/CH/flat/64.png"),
//                     new Pays("Syria", "https://flagsapi.com/SY/flat/64.png"),
//                     new Pays("Tajikistan", "https://flagsapi.com/TJ/flat/64.png"),
//                     new Pays("Tanzania", "https://flagsapi.com/TZ/flat/64.png"),
//                     new Pays("Thailand", "https://flagsapi.com/TH/flat/64.png"),
//                     new Pays("Togo", "https://flagsapi.com/TG/flat/64.png"),
//                     new Pays("Tonga", "https://flagsapi.com/TO/flat/64.png"),
//                     new Pays("Trinidad and Tobago", "https://flagsapi.com/TT/flat/64.png"),
//                     new Pays("Tunisia", "https://flagsapi.com/TN/flat/64.png"),
//                     new Pays("Turkey", "https://flagsapi.com/TR/flat/64.png"),
//                     new Pays("Turkmenistan", "https://flagsapi.com/TM/flat/64.png"),
//                     new Pays("Tuvalu", "https://flagsapi.com/TV/flat/64.png"),
//                     new Pays("Uganda", "https://flagsapi.com/UG/flat/64.png"),
//                     new Pays("Ukraine", "https://flagsapi.com/UA/flat/64.png"),
//                     new Pays("United Arab Emirates", "https://flagsapi.com/AE/flat/64.png"),
//                     new Pays("United States", "https://flagsapi.com/US/flat/64.png"),
//                     new Pays("Uruguay", "https://flagsapi.com/UY/flat/64.png"),
//                     new Pays("Uzbekistan", "https://flagsapi.com/UZ/flat/64.png"),
//                     new Pays("Vanuatu", "https://flagsapi.com/VU/flat/64.png"),
//                     new Pays("Venezuela", "https://flagsapi.com/VE/flat/64.png"),
//                     new Pays("Vietnam", "https://flagsapi.com/VN/flat/64.png"),
//                     new Pays("Virgin Islands", "https://flagsapi.com/VI/flat/64.png"),
//                     new Pays("Yemen", "https://flagsapi.com/YE/flat/64.png"),
//                     new Pays("Zambia", "https://flagsapi.com/ZM/flat/64.png"),
//                     new Pays("Zimbabwe", "https://flagsapi.com/ZW/flat/64.png"));
//           paysService.deleteAllPays();

//           // Ajouter les pays s'ils n'existent pas déjà
//           for (Pays pays : paysList) {
//                if (!paysService.existsByNom(pays.getNom())) {
//                     paysService.save(pays);
//                }
//           }
//      }
// }